name: flex_yemen_ultimate
description: Flex Yemen Ultimate App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.png"
  adaptive_icon_background: "#D4AF37"
  adaptive_icon_foreground: "assets/icon/logo.png"
